@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "feat: complete attendance system with face recognition and admin panel" || echo Nothing to commit
echo Renaming branch...
git branch -M main
echo Adding remote...
git remote add origin https://github.com/wintararaj-cmd/Attendance.git 2>NUL
if %errorlevel% neq 0 (
    echo Remote already exists, updating URL...
    git remote set-url origin https://github.com/wintararaj-cmd/Attendance.git
)
echo Pushing to GitHub...
git push -u origin main
pause
